---
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
- package-ecosystem: "terraform"
  directory: "/fixture/terraform"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    major-updates:
      applies-to: version-updates
      update-types:
      - "major"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 2
- package-ecosystem: "terraform"
  directory: "/fixture/terraform_with_changes"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    major-updates:
      applies-to: version-updates
      update-types:
      - "major"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 2
- package-ecosystem: "terraform"
  directory: "/fixture/terraform_with_failed_plan"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    major-updates:
      applies-to: version-updates
      update-types:
      - "major"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 2
