---
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2

- package-ecosystem: "terraform"
  directory: "/fixture/terraform"
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Oslo"
  open-pull-requests-limit: 0 # Security-updates only

- package-ecosystem: "terraform"
  directory: "/fixture/terraform_with_changes"
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Oslo"
  open-pull-requests-limit: 0 # Security-updates only

- package-ecosystem: "terraform"
  directory: "/fixture/terraform_with_failed_plan"
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Oslo"
  open-pull-requests-limit: 0 # Security-updates only