name: Entur/Terraform/Apply

on:
  workflow_call:
    inputs:
      directory:
        description: "Path to Terraform Directory"
        type: string
        default: "terraform"
      cloud_provider:
        description: "The cloud provider for this project"
        type: string
        default: "GCP"
      environment:
        description: "The cloud environment"
        type: string
        default: "dev"
      workspace:
        description: "The terraform workspace, defaults to env"
        type: string
        default: "env"
      version:
        description: "Terraform version"
        type: string
        default: "latest"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_TERRAFORM_FORCE_APPLY_DIRECTORY=${{ inputs.directory }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_FORCE_APPLY_CLOUD_PROVIDER=${{ inputs.cloud_provider }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_FORCE_APPLY_ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_FORCE_APPLY_WORKSPACE=${{ inputs.workspace }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_FORCE_APPLY_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - id: set-workspace
        shell: bash
        run: |
          if [[ "${{ env.GHA_TERRAFORM_FORCE_APPLY_WORKSPACE }}" = "env" ]]; then
            echo "GHA_TERRAFORM_FORCE_APPLY_WORKSPACE=${{ env.GHA_TERRAFORM_FORCE_APPLY_ENVIRONMENT }}" >> $GITHUB_ENV
          fi

      - name: checkout
        uses: actions/checkout@v4

      - name: Access GCP
        id: login-gcp
        uses: google-github-actions/auth@v2.1.2
        if: env.GHA_TERRAFORM_FORCE_APPLY_CLOUD_PROVIDER == 'GCP'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Access GKE cluster
        id: get-credentials-gcp
        uses: google-github-actions/get-gke-credentials@v2
        if: env.GHA_TERRAFORM_FORCE_APPLY_CLOUD_PROVIDER == 'GCP'
        with:
          project_id: "ent-kub-${{inputs.environment}}" # TODO: fix jp
          cluster_name: "kub-ent-${{inputs.environment}}-001" # TODO: fix jp
          location: "europe-west1" # TODO: fix jp

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        id: setup
        with:
          terraform_version: ${{ env.GHA_TERRAFORM_FORCE_APPLY_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        working-directory: ${{ env.GHA_TERRAFORM_FORCE_APPLY_DIRECTORY }}
        shell: bash
        run: |
          terraform init

      - name: Terraform Workspace
        id: workspace
        working-directory: ${{ env.GHA_TERRAFORM_FORCE_APPLY_DIRECTORY }}
        shell: bash
        run: |
          terraform workspace select ${{ env.GHA_TERRAFORM_FORCE_APPLY_WORKSPACE }} -or-create=true

      - name: Terraform Apply
        id: force-apply
        working-directory: ${{ env.GHA_TERRAFORM_FORCE_APPLY_DIRECTORY }}
        shell: bash
        run: |
          echo 'apply<<EOF' >> $GITHUB_OUTPUT
          terraform apply --auto-approve -var-file=env/${{ env.GHA_TERRAFORM_FORCE_APPLY_ENVIRONMENT }}.tfvars -input=false -no-color >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Update Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && env.GHA_TERRAFORM_FORCE_APPLY_DEPLOY == 'true'
        with:
          script: |
            const output = `#### Terraform Apply 📖\`${{ steps.apply.outcome }}\`
            <details><summary>Show Apply</summary>

            \`\`\`tf\n
            ${{ steps.apply.outputs.apply }}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Apply Status
        if: steps.apply.outcome == 'failure'
        run: exit 1
