name: Entur/Terraform/Apply

on:
  workflow_call:
    inputs:
      directory:
        description: "Path to Terraform Directory"
        type: string
        default: "terraform"
      cloud_provider:
        description: "The cloud provider for this project"
        type: string
        default: "GCP"
      environment:
        description: "The cloud environment"
        type: string
        default: "dev"
      workspace:
        description: "The terraform workspace, defaults to env"
        type: string
        default: "env"
      version:
        description: "Terraform version"
        type: string
        default: "latest"
      project_id:
        type: string
        description: "Do not use this input"
      cluster_name:
        type: string
        description: "Do not use this input"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_TERRAFORM_FORCE_APPLY_DIRECTORY=${{ inputs.directory }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_FORCE_APPLY_CLOUD_PROVIDER=${{ inputs.cloud_provider }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_FORCE_APPLY_ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_FORCE_APPLY_WORKSPACE=${{ inputs.workspace }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_FORCE_APPLY_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - id: set-workspace
        shell: bash
        run: |
          if [[ "${{ env.GHA_TERRAFORM_FORCE_APPLY_WORKSPACE }}" = "env" ]]; then
            echo "GHA_TERRAFORM_FORCE_APPLY_WORKSPACE=${{ env.GHA_TERRAFORM_FORCE_APPLY_ENVIRONMENT }}" >> $GITHUB_ENV
          fi

      - name: checkout
        uses: actions/checkout@v4

      - uses: entur/gha-meta/.github/actions/cloud-auth@v1.1.1
        with:
          environment: ${{ env.GHA_TERRAFORM_FORCE_APPLY_ENVIRONMENT }}
          cloud_provider: ${{ env.GHA_TERRAFORM_FORCE_APPLY_CLOUD_PROVIDER }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: entur/gha-meta/.github/actions/k8s-auth@v1.1.1
        with:
          environment: ${{ env.GHA_TERRAFORM_FORCE_APPLY_ENVIRONMENT }}
          cloud_provider: ${{ env.GHA_TERRAFORM_FORCE_APPLY_CLOUD_PROVIDER }}
          project_id: ${{ inputs.project_id }}
          cluster_name: ${{ inputs.cluster_name }}
          azure_cluster_resource_group: ${{ vars.AZURE_CLUSTER_RESOURCE_GROUP }}
          azure_cluster_name: ${{ vars.AZURE_CLUSTER_NAME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        id: setup
        with:
          terraform_version: ${{ env.GHA_TERRAFORM_FORCE_APPLY_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        working-directory: ${{ env.GHA_TERRAFORM_FORCE_APPLY_DIRECTORY }}
        shell: bash
        run: |
          terraform init

      - name: Terraform Workspace
        id: workspace
        working-directory: ${{ env.GHA_TERRAFORM_FORCE_APPLY_DIRECTORY }}
        shell: bash
        run: |
          terraform workspace select -or-create=true ${{ env.GHA_TERRAFORM_FORCE_APPLY_WORKSPACE }}

      - name: Terraform Apply
        id: force-apply
        working-directory: ${{ env.GHA_TERRAFORM_FORCE_APPLY_DIRECTORY }}
        shell: bash
        run: |
          echo 'apply<<EOF' >> $GITHUB_OUTPUT
          terraform apply --auto-approve -var-file=env/${{ env.GHA_TERRAFORM_FORCE_APPLY_ENVIRONMENT }}.tfvars -input=false -no-color >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Print Apply Log
        id: print-apply-log
        shell: bash
        run: |
          echo "${{ steps.force-apply.outputs.apply }}"

      - name: Get Pull Request Number
        id: get-pr-number
        run: echo "GHA_TERRAFORM_FORCE_APPLY_PULL_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> $GITHUB_ENV
        shell: bash

      - name: Update Pull Request
        uses: actions/github-script@v7
        if: env.GHA_TERRAFORM_FORCE_APPLY_PULL_NUMBER != ''
        with:
          script: |
            const output = `#### Terraform Apply 📖\`${{ steps.apply.outcome }}\`
            <details><summary>Show Apply</summary>

            \`\`\`tf\n
            ${{ steps.force-apply.outputs.apply }}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: ${{ env.GHA_TERRAFORM_FORCE_APPLY_PULL_NUMBER }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Apply Status
        if: steps.force-apply.outcome == 'failure'
        run: exit 1
