name: Entur/Terraform/Apply

on:
  workflow_call:
    inputs:
      tf_directory:
        description: "Path to Terraform Directory"
        type: string
        default: "terraform"
      cloud_provider:
        description: "The cloud provider for this project"
        type: string
        default: "GCP"
      environment:
        description: "The cloud environment"
        type: string
        default: "dev"
      tf_workspace:
        description: "The terraform workspace"
        type: string
        default: "dev"
      tf_version:
        description: "Terraform version"
        type: string
        default: "latest"
      tf_deploy:
        description: "Deploy terraform infrastructure"
        type: boolean
        default: true


jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_TERRAFORM_DIRECTORY=${{ inputs.tf_directory }}" >> $GITHUB_ENV
          echo "GHA_CLOUD_PROVIDER=${{ inputs.cloud_provider }}" >> $GITHUB_ENV
          echo "GHA_ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_WORKSPACE=${{ inputs.tf_workspace }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_VERSION=${{ inputs.tf_version }}" >> $GITHUB_ENV
          echo "GHA_TERRAFORM_DEPLOY=${{ inputs.tf_deploy }}" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v4

      - name: Access gcp
        id: login-gcp
        uses: google-github-actions/auth@v2.1.2
        if: env.GHA_CLOUD_PROVIDER == 'GCP'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        id: setup
        with:
          terraform_version: ${{ env.GHA_TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
        shell: bash
        run: |
          terraform init

      - name: Terraform Workspace
        id: workspace
        working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
        shell: bash
        run: |
          terraform workspace select ${{ env.GHA_TERRAFORM_WORKSPACE }} || terraform workspace new ${{ env.GHA_TERRAFORM_WORKSPACE }}


      - name: Terraform Apply
        id: force-apply
        working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
        shell: bash
        if: env.GHA_TERRAFORM_DEPLOY == true
        run: |
          echo 'apply<<EOF' >> $GITHUB_OUTPUT
          terraform apply --auto-approve -var-file=env/${{ env.GHA_ENVIRONMENT }}.tf -input=false -no-color >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT