on:
  workflow_call:
    inputs:
      terraform_dir:
        description: "Path to Terraform Directory"
        type: string
        default: "terraform"
      cloud_provider:
        description: "The cloud provider, options are gcloud or azure"
        type: string
        default: "gcloud"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_wrapper: true
      - run: tflint --version
      - run: tflint --init
      - run: tflint --chdir=${{ inputs.terraform_dir }} -f json