name: Entur/Terraform/Lint

on:
  workflow_call:
    inputs:
      directory:
        description: "Path to Terraform Directory"
        type: string
        default: "terraform"
      version:
        description: "Terraform version"
        type: string
        default: "latest"
      timeout_minutes:
        description: "Job timeout in minutes"
        type: number
        default: 5
env:
  GHA_TERRAFORM_LINT_DIRECTORY: ${{ inputs.directory }}
  GHA_TERRAFORM_LINT_VERSION: ${{ inputs.version }}
jobs:
  lint:
    name: Terraform Lint
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.GHA_TERRAFORM_LINT_VERSION }}
          terraform_wrapper: false
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_wrapper: true
      - run: terraform fmt -check
      - run: |
          tflint --init
          tflint --chdir=${GHA_TERRAFORM_LINT_DIRECTORY} -f compact
