name: Entur/Terraform/Lint

on:
  workflow_call:
    inputs:
      directory:
        description: "Path to Terraform Directory"
        type: string
        default: "terraform"
      version:
        description: "Terraform version, nb: Setting this, overrides the version defined in code. If not set in code, the latest version is used."
        type: string
        default: "latest"
      timeout_minutes:
        description: "Job timeout in minutes"
        type: number
        default: 5
    outputs:
      version:
        description: "Terraform version"
        value: ${{ jobs.lint.outputs.version }}
jobs:
  lint:
    name: Terraform Lint
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    env:
      GHA_TERRAFORM_DIRECTORY: ${{ inputs.directory }}
      GHA_TERRAFORM_VERSION: ${{ inputs.version }}
    permissions:
      contents: read
    outputs:
      version: ${{ steps.set-terraform-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: "Terraform Version Action"
        id: set-terraform-version
        uses: entur/gha-terraform/.github/actions/terraform-version@v2
        with:
          directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
          version: ${{ env.GHA_TERRAFORM_VERSION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.set-terraform-version.outputs.version }}
          terraform_wrapper: false
      - uses: terraform-linters/setup-tflint@v5
        with:
          tflint_wrapper: true
      - run: |
          LINT=TESTS
          RED='\033[0;31m'
          GREEN='\033[0;32m'
          YELLOW='\033[0;33m'
          NEUTRAL='\033[0m'
          printf "%bChecking Terraform files for formatting issues: %b\n" "${YELLOW}" "${NEUTRAL}"
          printf "#--------------------------------------------------------------------------------\n"
          if ! terraform -chdir=${GHA_TERRAFORM_DIRECTORY} fmt -check -recursive; then
            printf "#--------------------------------------------------------------------------------\n"
            printf "%bERROR%b: Terraform files are not formatted correctly\n" "${RED}" "${NEUTRAL}"
            printf "Please run 'terraform fmt -recursive' to fix the formatting issues in the files listed above.\n"
            printf "PS: You can most likely find a terraform plugin or mode for your editor that can format on save, or as you type. If none is provided, you can use the 'terraform-ls' language server."
            echo "## :x: Lint Failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            printf "Formating: %bOK%b\n\n" "${GREEN}" "${NEUTRAL}"
          fi


          printf "%bRunning TFLint: %b\n" "${YELLOW}" "${NEUTRAL}"
          printf "#--------------------------------------------------------------------------------\n"
          tflint --init
          if ! tflint --chdir=${GHA_TERRAFORM_DIRECTORY} --recursive; then
            printf "#--------------------------------------------------------------------------------\n"
            printf "%bERROR%b: TFLint found issues in the Terraform configuration\n" "${RED}" "${NEUTRAL}"
            printf "Please check the error messages above and fix the issue\n\n"
            echo "## :x: Lint Failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            printf "TFLint: %bOK%b\n\n" "${GREEN}" "${NEUTRAL}"
          fi

          printf "%bInitializing Terraform Configuration to check for provider plugins issues: %b\n" "${YELLOW}" "${NEUTRAL}"
          printf "#--------------------------------------------------------------------------------\n"
          if ! terraform -chdir=${GHA_TERRAFORM_DIRECTORY} init -backend=false; then
            printf "#----------------------------------------\n"
            printf "\n%bERROR%b: Terraform configuration could not be initialized\n" "${RED}" "${NEUTRAL}"
            printf "Please check the error messages above and fix the issue\n\n"
            echo "## :x: Lint Failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            printf "Initialization: %bOK%b\n\n" "${GREEN}" "${NEUTRAL}"
          fi

          printf "%bValidating Terraform Configuration: %b\n" "${YELLOW}" "${NEUTRAL}"
          printf "#--------------------------------------------------------------------------------\n"
          if ! terraform -chdir=${GHA_TERRAFORM_DIRECTORY} validate; then
            printf "#--------------------------------------------------------------------------------\n"
            printf "\n%bERROR%b: Terraform configuration is not valid\n" "${RED}" "${NEUTRAL}"
            printf "Please check the error messages above and fix the issue\n\n"
            echo "## :x: Lint Failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            printf "Validation: %bOK%b\n\n" "${GREEN}" "${NEUTRAL}"
          fi
          echo "## :white_check_mark: Lint" >> $GITHUB_STEP_SUMMARY
