name: Entur/Terraform/Lint

on:
  workflow_call:
    inputs:
      directory:
        description: "Path to Terraform Directory"
        type: string
        default: "terraform"

jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_TERRAFORM_LINT_DIRECTORY=${{ inputs.directory }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_wrapper: true
      - run: terraform fmt -check
      - run: tflint --version
      - run: tflint --init
      - run: tflint --chdir=${{ env.GHA_TERRAFORM_LINT_DIRECTORY }} -f compact
