name: Entur/Terraform/NegativeTests

on:
  pull_request:


jobs:
  test-terraform-plan-with-failures:
   name: This job should fail
   uses: ./.github/workflows/plan.yml
   with:
     directory: fixture/terraform_with_failed_plan
     version: 1.8.3
     environment: dev
   secrets: inherit